/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CampagnesRouteImport } from './routes/campagnes'
import { Route as InstellingenRouteImport } from './routes/instellingen'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as ContactenContactIdRouteImport } from './routes/contacten.$contactId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CampagnesRoute = CampagnesRouteImport.update({
  id: '/campagnes',
  path: '/campagnes',
  getParentRoute: () => rootRouteImport,
} as any)
const InstellingenRoute = InstellingenRouteImport.update({
  id: '/instellingen',
  path: '/instellingen',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactenContactIdRoute = ContactenContactIdRouteImport.update({
  id: '/contacten/$contactId',
  path: '/contacten/$contactId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/campagnes': typeof CampagnesRoute
  '/instellingen': typeof InstellingenRoute
  '/pipeline': typeof PipelineRoute
  '/contacten/$contactId': typeof ContactenContactIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/campagnes': typeof CampagnesRoute
  '/instellingen': typeof InstellingenRoute
  '/pipeline': typeof PipelineRoute
  '/contacten/$contactId': typeof ContactenContactIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/campagnes': typeof CampagnesRoute
  '/instellingen': typeof InstellingenRoute
  '/pipeline': typeof PipelineRoute
  '/contacten/$contactId': typeof ContactenContactIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/campagnes'
    | '/instellingen'
    | '/pipeline'
    | '/contacten/$contactId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/campagnes'
    | '/instellingen'
    | '/pipeline'
    | '/contacten/$contactId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/campagnes'
    | '/instellingen'
    | '/pipeline'
    | '/contacten/$contactId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CampagnesRoute: typeof CampagnesRoute
  InstellingenRoute: typeof InstellingenRoute
  PipelineRoute: typeof PipelineRoute
  ContactenContactIdRoute: typeof ContactenContactIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campagnes': {
      id: '/campagnes'
      path: '/campagnes'
      fullPath: '/campagnes'
      preLoaderRoute: typeof CampagnesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instellingen': {
      id: '/instellingen'
      path: '/instellingen'
      fullPath: '/instellingen'
      preLoaderRoute: typeof InstellingenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacten/$contactId': {
      id: '/contacten/$contactId'
      path: '/contacten/$contactId'
      fullPath: '/contacten/$contactId'
      preLoaderRoute: typeof ContactenContactIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CampagnesRoute: CampagnesRoute,
  InstellingenRoute: InstellingenRoute,
  PipelineRoute: PipelineRoute,
  ContactenContactIdRoute: ContactenContactIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
