/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BenaderdRouteImport } from './routes/benaderd'
import { Route as CampagnesRouteImport } from './routes/campagnes'
import { Route as InstellingenRouteImport } from './routes/instellingen'
import { Route as OverzichtRouteImport } from './routes/overzicht'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as ContactenContactIdRouteImport } from './routes/contacten.$contactId'
import { Route as ApiPublicAssistantRunRouteImport } from './routes/api/public/assistant-run'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BenaderdRoute = BenaderdRouteImport.update({
  id: '/benaderd',
  path: '/benaderd',
  getParentRoute: () => rootRouteImport,
} as any)
const CampagnesRoute = CampagnesRouteImport.update({
  id: '/campagnes',
  path: '/campagnes',
  getParentRoute: () => rootRouteImport,
} as any)
const InstellingenRoute = InstellingenRouteImport.update({
  id: '/instellingen',
  path: '/instellingen',
  getParentRoute: () => rootRouteImport,
} as any)
const OverzichtRoute = OverzichtRouteImport.update({
  id: '/overzicht',
  path: '/overzicht',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactenContactIdRoute = ContactenContactIdRouteImport.update({
  id: '/contacten/$contactId',
  path: '/contacten/$contactId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAssistantRunRoute = ApiPublicAssistantRunRouteImport.update({
  id: '/api/public/assistant-run',
  path: '/api/public/assistant-run',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/benaderd': typeof BenaderdRoute
  '/campagnes': typeof CampagnesRoute
  '/instellingen': typeof InstellingenRoute
  '/overzicht': typeof OverzichtRoute
  '/pipeline': typeof PipelineRoute
  '/contacten/$contactId': typeof ContactenContactIdRoute
  '/api/public/assistant-run': typeof ApiPublicAssistantRunRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/benaderd': typeof BenaderdRoute
  '/campagnes': typeof CampagnesRoute
  '/instellingen': typeof InstellingenRoute
  '/overzicht': typeof OverzichtRoute
  '/pipeline': typeof PipelineRoute
  '/contacten/$contactId': typeof ContactenContactIdRoute
  '/api/public/assistant-run': typeof ApiPublicAssistantRunRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/benaderd': typeof BenaderdRoute
  '/campagnes': typeof CampagnesRoute
  '/instellingen': typeof InstellingenRoute
  '/overzicht': typeof OverzichtRoute
  '/pipeline': typeof PipelineRoute
  '/contacten/$contactId': typeof ContactenContactIdRoute
  '/api/public/assistant-run': typeof ApiPublicAssistantRunRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/benaderd'
    | '/campagnes'
    | '/instellingen'
    | '/overzicht'
    | '/pipeline'
    | '/contacten/$contactId'
    | '/api/public/assistant-run'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/benaderd'
    | '/campagnes'
    | '/instellingen'
    | '/overzicht'
    | '/pipeline'
    | '/contacten/$contactId'
    | '/api/public/assistant-run'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/benaderd'
    | '/campagnes'
    | '/instellingen'
    | '/overzicht'
    | '/pipeline'
    | '/contacten/$contactId'
    | '/api/public/assistant-run'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BenaderdRoute: typeof BenaderdRoute
  CampagnesRoute: typeof CampagnesRoute
  InstellingenRoute: typeof InstellingenRoute
  OverzichtRoute: typeof OverzichtRoute
  PipelineRoute: typeof PipelineRoute
  ContactenContactIdRoute: typeof ContactenContactIdRoute
  ApiPublicAssistantRunRoute: typeof ApiPublicAssistantRunRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benaderd': {
      id: '/benaderd'
      path: '/benaderd'
      fullPath: '/benaderd'
      preLoaderRoute: typeof BenaderdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campagnes': {
      id: '/campagnes'
      path: '/campagnes'
      fullPath: '/campagnes'
      preLoaderRoute: typeof CampagnesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instellingen': {
      id: '/instellingen'
      path: '/instellingen'
      fullPath: '/instellingen'
      preLoaderRoute: typeof InstellingenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overzicht': {
      id: '/overzicht'
      path: '/overzicht'
      fullPath: '/overzicht'
      preLoaderRoute: typeof OverzichtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacten/$contactId': {
      id: '/contacten/$contactId'
      path: '/contacten/$contactId'
      fullPath: '/contacten/$contactId'
      preLoaderRoute: typeof ContactenContactIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/assistant-run': {
      id: '/api/public/assistant-run'
      path: '/api/public/assistant-run'
      fullPath: '/api/public/assistant-run'
      preLoaderRoute: typeof ApiPublicAssistantRunRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BenaderdRoute: BenaderdRoute,
  CampagnesRoute: CampagnesRoute,
  InstellingenRoute: InstellingenRoute,
  OverzichtRoute: OverzichtRoute,
  PipelineRoute: PipelineRoute,
  ContactenContactIdRoute: ContactenContactIdRoute,
  ApiPublicAssistantRunRoute: ApiPublicAssistantRunRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
